apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: konflux demo tests
spec:
  description: >-
    Expects a list of container images to be provided via the SNAPSHOT parameter.
  params:
    - name: SNAPSHOT
      description: A list of container images that should undergo testing
      type: string
    - name: GIT_URL
      description: URL of the GIT repository that contains the tests.
      default: "https://github.com/libhe/konfluxdemo"
      type: string
    - name: GIT_REF
      default: "master"
      description: Branch of the git repository used containing the tests
      type: string
    - name: DEBUG_OUTPUT
      default: "0"
      type: string
    - name: WAIVE
      default: "0"
      type: string
    - name: SKIP
      default: "0"
      type: string
  tasks:
    - name: task-1
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
        - name: SNAPSHOT
        results:
        - name: TEST_OUTPUT
          description: Test outpu
        steps:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          script: |
            dnf -y install jq
            echo -e "Example test task for the Snapshot:\n ${SNAPSHOT}"
            # Run custom tests for the given Snapshot here
            # After the tests finish, record the overall result in the RESULT variable
            RESULT="SUCCESS"